# Generated by Django 4.2.7 on 2026-06-22 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'بالا'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('send_to_all', models.BooleanField(default=True, verbose_name='ارسال به همه کاربران')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='تعداد گیرنده\u200cها')),
                ('success_count', models.IntegerField(default=0, verbose_name='تعداد موفق')),
                ('failed_count', models.IntegerField(default=0, verbose_name='تعداد ناموفق')),
                ('schedule_for', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('target_users', models.ManyToManyField(blank=True, related_name='broadcast_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربران هدف')),
            ],
            options={
                'verbose_name': 'پیام همگانی',
                'verbose_name_plural': 'پیام\u200cهای همگانی',
                'db_table': 'broadcast_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
