# Generated by Django 4.2.7 on 2026-06-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_type', models.CharField(choices=[('register', 'ثبت\u200cنام'), ('reset_password', 'بازیابی رمز عبور')], default='register', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code'], name='email_verif_email_d445b4_idx'), models.Index(fields=['verification_type', 'is_used'], name='email_verif_verific_4f45cc_idx')],
            },
        ),
    ]
