# Generated by Django 4.2.7 on 2026-06-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Display Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('daily_limit', models.IntegerField(default=500, verbose_name='Daily Limit')),
                ('sent_today', models.IntegerField(default=0, verbose_name='Sent Today')),
                ('last_reset', models.DateField(auto_now_add=True, verbose_name='Last Reset')),
                ('total_sent', models.IntegerField(default=0, verbose_name='Total Sent')),
                ('total_success', models.IntegerField(default=0, verbose_name='Total Success')),
                ('total_failed', models.IntegerField(default=0, verbose_name='Total Failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
                'db_table': 'smtp_settings',
                'ordering': ['-is_default', '-is_active'],
            },
        ),
    ]
