# Generated by Django 4.2.7 on 2026-06-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('verification', 'کد تایید ثبت\u200cنام'), ('reset_password', 'بازیابی رمز عبور'), ('welcome', 'خوش\u200cآمدگویی'), ('campaign', 'کمپین ایمیل')], max_length=20, unique=True, verbose_name='Template Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('body', models.TextField(verbose_name='Email Body (HTML)')),
                ('variables', models.TextField(blank=True, null=True, verbose_name='Available Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
            },
        ),
        migrations.AddField(
            model_name='smtpsetting',
            name='name',
            field=models.CharField(default='Default', max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Recipient')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('status', models.CharField(choices=[('success', '✅ موفق'), ('failed', '❌ ناموفق'), ('pending', '⏳ در انتظار')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('smtp_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.smtpsetting', verbose_name='SMTP Setting')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
