# Generated by Django 4.2.7 on 2026-06-21 10:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('daily_limit', models.IntegerField(default=400)),
                ('sent_today', models.IntegerField(default=0)),
                ('last_reset', models.DateField(auto_now_add=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_success', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'senders',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SenderGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('senders', models.ManyToManyField(related_name='groups', to='senders.sender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sender_groups',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
